brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/',include('todos.urls'))
]

todos/urls.py
from django.urls import path 

#from todos.views import TodoListList

#urlpatterns =[
  #  path("", TodoListView.as_view(), name = "todo_list")
#]

from todos.views import (TodoListListView,  TodoListDetailView, TodoListCreateView)

    

urlpatterns = [
    #make path, name of class, url path
    path("", TodoListListView.as_view(), name="todo_list_list"),
    path("<int:pk>/", TodoListDetailView.as_view(), name="todo_list_detail"),
    path("create/", TodoListCreateView.as_view(), name="todo_list_create")]

todos/models.py
from django.db import models

# Create your models here.

#creating a Todolist Model that will allow us to make a list
class TodoList(models.Model):
    #have to give todo list a name
    name = models.CharField(max_length = 100)
    #When was the list created
    created_on = models.DateTimeField(auto_now_add=True)
    # a function that will return the name of the list
    def __str__(self):
        return self.name 

#create a todoItem Model that will allow me populate my todolsit
class TodoItem(models.Model):
    #name a task
    task = models.CharField(max_length=100)
    #duedate property, it is optional! 
    due_date =models.DateTimeField(null=True, blank=True )
    #is complete property, a boolean??
    is_completed =models.BooleanField(default=False)
    # a foreign key relationship, cascade.delete 
    list= models.ForeignKey("TodoList", related_name="items", on_delete=models.CASCADE)
    # a function that returns the value of the items 
    def __str__(self):
        return self.task 

todos/views.py
from django.shortcuts import render

from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView 
from django.views.generic.list import ListView
 
from todos.models import TodoList
 
 
class TodoListListView(ListView):
   model = TodoList
   template_name = "todo_lists/list.html"
 
 
class TodoListDetailView(DetailView):
   model = TodoList
   template_name = "todo_lists/detail.html"
 
 
class TodoListCreateView(CreateView):
   model = TodoList
   template_name = "todo_lists/create.html"
   fields = ["name"]
 
   def get_success_url(self):
       return reverse_lazy("todo_list_detail", args=[self.object.id])
 
 
 

todos/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Todo Lists</title>
</head>
<body>
  {% block content %}
  {% endblock content %}
</body>
</html>

todos/templates/todo_items/create.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button>Submit</button>
    </form>
  </main>
{% endblock content %}

todos/templates/todo_items/update.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button>Submit</button>
    </form>
  </main>
{% endblock content %}

todos/templates/todo_list/create.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button>Submit</button>
    </form>
  </main>
{% endblock content %}

todos/templates/todo_list/delete.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button>Submit</button>
    </form>
  </main>
{% endblock content %}

todos/templates/todo_list/detail.html
{% extends 'base.html' %}
 
{% block content %}
 <main>
   <a href="{% url 'todo_list_list' %}">Back to list</a>
   <h1>{{ todolist.name }}</h1>
   <h2>Tasks</h2>
   <table>
     <thead>
       <tr>
         <th>Task</th>
         <th>Due date</th>
       </tr>
     </thead>
     <tbody>
       {% for item in todolist.items.all %}
         <tr>
           <td>
               {{ item.task }}
             </a>
           </td>
           <td>{{ item.due_date|date:"M d, Y"}}</td>
         </tr>
       {% endfor %}
     </tbody>
   </table>
 </main>
{% endblock content %}

todos/templates/todo_list/list.html
{% extends 'base.html' %}
 
{% block content %}
 <main>
   <h1>My lists</h1>
   <a href="{% url 'todo_list_create' %}">Create a new list</a>
   <a href="{% url 'todo_item_create' %}">Create a new item</a>
   <table>
     <thead>
       <tr>
         <th>Name</th>
         <th>Number of items</th>
       </tr>
     </thead>
     <tbody>
       {% for list in todolist_list %}
         <tr>
           <td>
             <a href="{% url 'todo_list_detail' list.id %}">
               {{ list.name }}
             </a>
           </td>
           <td>{{ list.items.all|length }}</td>
         </tr>
       {% endfor %}
     </tbody>
   </table>
 </main>
{% endblock content %}

todos/templates/todo_list/update.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button>Submit</button>
    </form>
  </main>
{% endblock content %}